/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class nautilus_lab_graphics_Camera3D */

#ifndef _Included_nautilus_lab_graphics_Camera3D
#define _Included_nautilus_lab_graphics_Camera3D
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     nautilus_lab_graphics_Camera3D
 * Method:    initCamera
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_nautilus_lab_graphics_Camera3D_initCamera
  (JNIEnv *, jobject);

/*
 * Class:     nautilus_lab_graphics_Camera3D
 * Method:    lookAt
 * Signature: (JFFFFFFFFF)V
 */
JNIEXPORT void JNICALL Java_nautilus_lab_graphics_Camera3D_lookAt__JFFFFFFFFF
  (JNIEnv *, jobject, jlong, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     nautilus_lab_graphics_Camera3D
 * Method:    lookAt
 * Signature: (JFFFFFFFFF[F)V
 */
JNIEXPORT void JNICALL Java_nautilus_lab_graphics_Camera3D_lookAt__JFFFFFFFFF_3F
  (JNIEnv *, jobject, jlong, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloatArray);

/*
 * Class:     nautilus_lab_graphics_Camera3D
 * Method:    lookAt
 * Signature: (J[F[F[F[F)V
 */
JNIEXPORT void JNICALL Java_nautilus_lab_graphics_Camera3D_lookAt__J_3F_3F_3F_3F(JNIEnv *, jobject, jlong, jfloatArray, jfloatArray, jfloatArray, jfloatArray);

/*
 * Class:     nautilus_lab_graphics_Camera3D
 * Method:    perspective
 * Signature: (JIIIIFFF)V
 */
JNIEXPORT void JNICALL Java_nautilus_lab_graphics_Camera3D_perspective
  (JNIEnv *, jobject, jlong, jint, jint, jint, jint, jfloat, jfloat, jfloat);

/*
 * Class:     nautilus_lab_graphics_Camera3D
 * Method:    project
 * Signature: (J[FFFF)V
 */
JNIEXPORT void JNICALL Java_nautilus_lab_graphics_Camera3D_project
  (JNIEnv *, jobject, jlong, jfloatArray, jfloat, jfloat, jfloat);

/*
 * Class:     nautilus_lab_graphics_Camera3D
 * Method:    projectOrthor
 * Signature: (J[FFFF)V
 */
JNIEXPORT void JNICALL Java_nautilus_lab_graphics_Camera3D_projectOrthor
  (JNIEnv *, jobject, jlong, jfloatArray, jfloat, jfloat, jfloat);

/*
 * Class:     nautilus_lab_graphics_Camera3D
 * Method:    rotate
 * Signature: (JFFF)V
 */
JNIEXPORT void JNICALL Java_nautilus_lab_graphics_Camera3D_rotate
  (JNIEnv *, jobject, jlong, jfloat, jfloat, jfloat);

/*
 * Class:     nautilus_lab_graphics_Camera3D
 * Method:    moveAlongForward
 * Signature: (JF)V
 */
JNIEXPORT void JNICALL Java_nautilus_lab_graphics_Camera3D_moveAlongForward
  (JNIEnv *, jobject, jlong, jfloat);

/*
 * Class:     nautilus_lab_graphics_Camera3D
 * Method:    jniRelease
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_nautilus_lab_graphics_Camera3D_jniRelease
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
