/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class simplemath_math_Function */

#ifndef _Included_simplemath_math_Function
#define _Included_simplemath_math_Function
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     simplemath_math_Function
 * Method:    jniInit
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_simplemath_math_Function_jniInit
  (JNIEnv *, jobject);

/*
 * Class:     simplemath_math_Function
 * Method:    jniSetString
 * Signature: (JLjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_simplemath_math_Function_jniSetString
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     simplemath_math_Function
 * Method:    jniCalc
 * Signature: (JLjava/lang/String;Lsimplemath/math/ReturnVal;)V
 */
JNIEXPORT void JNICALL Java_simplemath_math_Function_jniCalc
  (JNIEnv *, jobject, jlong, jstring, jobject);

/*
 * Class:     simplemath_math_Function
 * Method:    derivative
 * Signature: (JLsimplemath/math/Function;)I
 */
JNIEXPORT jint JNICALL Java_simplemath_math_Function_derivative
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     simplemath_math_Function
 * Method:    jniGetSpace
 * Signature: (J[FFZLjava/util/List;)V
 */
JNIEXPORT void JNICALL Java_simplemath_math_Function_jniGetSpace
  (JNIEnv *, jobject, jlong, jfloatArray, jfloat, jboolean, jobject);

/*
 * Class:     simplemath_math_Function
 * Method:    jniRelease
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_simplemath_math_Function_jniRelease
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
