/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>

/* Header for class nautilus_lab_graphics_Camera3D */

#ifndef _Included_nautilus_lab_graphics_Camera3D
#define _Included_nautilus_lab_graphics_Camera3D
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     nautilus_lab_graphics_Camera3D
 * Method:    initCamera
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL initCamera(JNIEnv *, jobject);

/*
 * Class:     nautilus_lab_graphics_Camera3D
 * Method:    lookAt
 * Signature: (JFFFFFFFFF)V
 */
JNIEXPORT void JNICALL lookAt
  (JNIEnv *, jobject, jlong, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     nautilus_lab_graphics_Camera3D
 * Method:    perspective
 * Signature: (JIIIIFFF)V
 */
JNIEXPORT void JNICALL perspective
  (JNIEnv *, jobject, jlong, jint, jint, jint, jint, jfloat, jfloat, jfloat);

/*
 * Class:     nautilus_lab_graphics_Camera3D
 * Method:    project
 * Signature: (J[FFFF)V
 */
JNIEXPORT void JNICALL project
  (JNIEnv *, jobject, jlong, jfloatArray, jfloat, jfloat, jfloat);

/*
 * Class:     nautilus_lab_graphics_Camera3D
 * Method:    projectOrthor
 * Signature: (J[FFFF)V
 */
JNIEXPORT void JNICALL projectOrthor
  (JNIEnv *, jobject, jlong, jfloatArray, jfloat, jfloat, jfloat);

/*
 * Class:     nautilus_lab_graphics_Camera3D
 * Method:    rotate
 * Signature: (JFFF)V
 */
JNIEXPORT void JNICALL rotate
  (JNIEnv *, jobject, jlong, jfloat, jfloat, jfloat);

/*
 * Class:     nautilus_lab_graphics_Camera3D
 * Method:    moveAlongForward
 * Signature: (JF)V
 */
JNIEXPORT void JNICALL moveAlongForward
  (JNIEnv *, jobject, jlong, jfloat);

/*
 * Class:     nautilus_lab_graphics_Camera3D
 * Method:    jniRelease
 * Signature: (J)V
 */
JNIEXPORT void JNICALL jniReleaseCam
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
